mode: MPIIGaze
device: cuda
dataset:
  dataset_dir: datasets/MPIIGaze.h5
model:
  name: gaze_net
train:
  batch_size: 256
  optimizer: adam
  base_lr: 0.00001
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001
  loss: L2
  seed: 0
  test_id: 0
  val_ratio: 0.1
  output_dir: experiments/mpiigaze/gaze_net/exp00
  log_period: 100
  checkpoint_period: 10
  use_tensorboard: True
  train_dataloader:
    num_workers: 4
    drop_last: True
    pin_memory: False
  val_dataloader:
    num_workers: 4
    pin_memory: False
scheduler:
  epochs: 15
  type: stepLR
  decaysteps: 5000
  decayratio: 0.1
cudnn:
  benchmark: True
  deterministic: False
optim:
  adam:
    betas: (0.9, 0.95)