mode: MPIIFaceGaze
device: cpu
model:
  name: resnet_simple
  backbone:
    name: resnet_simple
    pretrained: resnet18
    resnet_block: basic
    resnet_layers: [2, 2, 2]
gaze_estimator:
  checkpoint: data/mpiifacegaze_resnet_simple.pth
  camera_params: data/calib/sample_params.yaml
  normalized_camera_params: data/calib/normalized_camera_params_face.yaml
  normalized_camera_distance: 1.0
demo:
  use_camera: False
  display_on_screen: False
  wait_time: 1
  video_path: data/video/1.mp4
  output_dir: data/video/1-out
  output_file_extension: mp4
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.05
  show_bbox: False
  show_head_pose: False
  show_landmarks: True
  show_normalized_image: False
  show_template_model: False
