mode: MPIIGaze
device: cpu
model:
  name: resnet_preact
gaze_estimator:
  checkpoint: data/mpiigaze_resnet_preact.pth
  camera_params: data/calib/sample_params.yaml
  normalized_camera_params: data/calib/normalized_camera_params_eye.yaml
  normalized_camera_distance: 0.2
demo:
  use_camera: False
  display_on_screen: False
  wait_time: 1
  video_path: data/video/2.mp4
  output_dir: data/video/2-out.mp4
  output_file_extension: mp4
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.05
  show_bbox: True
  show_head_pose: True
  show_landmarks: True
  show_normalized_image: False
  show_template_model: False
